ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User.urls')),
    path('api/', include('TestAPI.urls')),
]

User/urls.py
from django.urls import path
from . import views


app_name = 'user'
urlpatterns = [
    path("login", views.LoginClass.as_view(), name="Index"),
    path("", views.ChatHomeClass.as_view(), name="ChatHome"),
    path("register", views.RegisterClass.as_view(), name="Register"),
    path("create", views.RegisterClass.as_view(),name="Create"),
    path("chat/<int:userID>", views.ChatClass.as_view(), name="ChatDetail"),
    path("search", views.SearchUser.as_view(), name="SearchUser"),
    path("info", views.InforUser.as_view(), name="InfoUser")
]

templates/chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chating</title>
    <link rel="stylesheet" href="{% static 'css/style.css' style.css %}">
    <link rel=" stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
</head>
<body>
    <div class="wrapper">
        <section class="chat-area">
            <header>

                <a href="{% url 'user:ChatHome' %}" class="back-icon"><i class="fas fa-arrow-left"></i></a>
                <img src="{{imguser}}" alt="">
                <div class="detail">
                    <span>{{user1.username}}</span>
                    <p>Active now</p>
                </div>
            </header>

            {% if empty == False %}
                <div class="chat-box" style="overflow-y: overlay;">
                    {% for message in messages|dictsort:"id"%}
                        {% if message.sender.id == user %}
                            <div class="chat outgoing">
                                <div class="detail">
                                    <p>{{ message.message}}</p>
                                </div>
                            </div>
                        {% else %}
                             <div class="chat incoming">
                                <img src="{{imguser}}" alt="">
                                <div class="detail">
                                    <p>{{ message.message}}</p>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% else %}
                <div class="chat-box" style="display: flex;    flex-direction: column;    justify-content: flex-end;">
                </div>
            {% endif %}

            <form action="{% url 'user:ChatDetail' user1.id %}" class="typing-area" method="post">
                {% csrf_token %}
                <input type="text" placeholder="Type messsage here...." name="message">
                <button><i class="fab fa-telegram-plane"></i></button>
            </form>
        </section>
        <script>
            var objDiv = document.querySelector(".chat-box");
            objDiv.scrollTop = objDiv.scrollHeight;
        </script>
</body>
</html>

templates/header.html
{% extends "login.html" %}

{% block head %}
    <div>
        <h1 style="background-color: #333;">Header</h1>
    </div>
{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/style.css' style.css %}">
    <link rel=" stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
</head>
<body>

    <div class="wrapper">
        <section class="form login">
            <header>Login</header>
            <form action="{% url 'user:Index' %}" method="post">
                 {% csrf_token %}

                 {% if message != none %}
                <div class="error-text" style="display: block;">{{message}}</div>
                {% else %}
                 <div class="error-text" style="display: none;"></div>
                {% endif %}
               
                <div class="field input">
                    <label>Username</label>
                    {{ login.username }}
                </div>

                <div class="field input">
                    <label>Password</label>
                    {{ login.password }}
                    <i class="fa-solid fa-eye"></i>
                </div>

                
                <div class="field button">
                    <input type="submit" value="Login">
                </div>
                <div class="link">Not yet signed up?<a href="{% url 'user:Register' %}">Sign up now</a></div>
            
            </form>
        </section>
    </div>
    <script src="{% static 'js/passShowHide.js'%}"></script>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
   <link rel="stylesheet" href="{% static 'css/style.css' style.css %}">
    <link rel=" stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
</head>
<body>
    <div class="wrapper">
        <section class="form signup">
            <header>Register</header>
            <form action="{% url 'user:Create' %}" method="post">
                {% csrf_token %}
                {% if message != none %}
                <div class="error-text" style="display: block;">{{message}}</div>
                {% else %}
                 <div class="error-text" style="display: none;"></div>
                {% endif %}
                <div class="name-detail">
                    <div class="field input">
                        <label>First name</label>
                        {{ l.first_name }}
                    </div>

                    <div class="field input">
                        <label>Last name</label>
                        {{ l.last_name }}
                    </div>
                </div>

                <div class="field input">
                    <label>Username</label>
                    {{ l.username }}
                </div>

                <div class="field input">
                    <label>Email</label>
                    {{ l.email }}

                </div>

                <div class="field input">
                    <label>Phone number</label>
                    {{ l.phone }}
                </div>

                <div class="field input">
                    <label>Password</label>
                    {{l.password}}
                    <i class="fa-solid fa-eye"></i>
                </div>

                <div class="field image">
                    <label>Image</label>
                    {{ l.image}}
                </div>
                <div class="field button">
                    <input type="submit" value="Register">
                </div>
                <div class="link">Already have account?<a href="{% url 'user:Index' %}">Login now</a></div>
            
            </form>
        </section>
    </div>

    <script src="{% static 'js/passShowHide.js'%}"></script>
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="style.css">
    <link rel=" stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
</head>
<body>
    <div class="header">
        {% block head %}
        {% endblock %}
    </div>
    <h1>Hiiii {{ name }}</h1>
    <h2>My asset</h2>
    <ul>
        {% for item in taisan %}
            {% if item == 'laptop' %}
            <li>
                <b>{{ item }}</b>
            </li>
            {% endif %}
            <li>
                <br>{{ item }}
            </li>
        {% endfor %}
    </ul>
    <div class="wrapper">
        <section class="form login">
            <header>Realtime chat App</header>
            <form action="#">
                <div class="error-text">This is error text</div>

                <div class="field input">
                    <label>Email</label>
                    <input type="text" placeholder="Enter your email">
                </div>

                <div class="field input">
                    <label>Password</label>
                    <input type="text" placeholder="Enter your password">
                    <i class="fa-solid fa-eye"></i>
                </div>


                <div class="field button">
                    <input type="submit" value="Register">
                </div>
                <div class="link">Not yet signed up?<a href="#">Sign up now</a></div>

            </form>
        </section>
    </div>
    <script src="js/passShowHide.js"></script>
</body>
</html>

templates/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update account</title>
   <link rel="stylesheet" href="{% static 'css/style.css' style.css %}">
    <link rel=" stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
</head>
<body>
    <div class="wrapper">
        <section class="form signup">
            <header>Update Account</header>
            <form action="{% url 'user:InfoUser' %}" method="post">
                {% csrf_token %}
                {% if message != none %}
                <div class="error-text" style="display: block;">{{message}}</div>
                {% else %}
                 <div class="error-text" style="display: none;"></div>
                {% endif %}
                <div class="name-detail">
                    <div class="field input">
                        <label>First name</label>
                        <input type="text" name="first_name" placeholder="First name" required="required"
                               maxlength="150" id="id_first_name" value="{{u.first_name}}">
                    </div>

                    <div class="field input">
                        <label>Last name</label>
                        <input type="text" name="last_name" placeholder="Last name" required="required" maxlength="150"
                               id="id_last_name"  value="{{u.last_name}}">
                    </div>
                </div>

                <div class="field input">
                    <label>Username</label>
                    <input type="text" name="username" placeholder="Enter your username" required=""
                           maxlength="150" aria-describedby="id_username_helptext" id="id_username" value="{{u.username}}">
                </div>

                <div class="field input">
                    <label>Email</label>
                    <input type="email" name="email" placeholder="Enter your email" required="required"
                           maxlength="254" value="{{u.email}}">

                </div>

                <div class="field input">
                    <label>Phone number</label>
                    <input type="text" name="phone" placeholder="Enter your email" required="required"
                           maxlength="254"  value="{{u.phone}}">
                </div>

                <div class="field input">
                    <label>Password</label>
                    <input type="password" name="password" placeholder="Enter your email" required="required"
                           maxlength="254" value="{{u.password}}">
                    <i class="fa-solid fa-eye"></i>
                </div>

                <div class="field image">
                    <label>Image</label>
                    <div class="image-input" style="display: flex;justify-content: space-around;align-items: center;">
                        <input type="File" name="image" maxlength="200" value="{{u.image}}" style="width: 110px;">
                        <img src="{{u.image}}" style="width: 100px; height: 100px;">
                    </div>

                </div>
                <div class="field button">
                    <input type="submit" value="Update">
                </div>

            
            </form>
        </section>
    </div>

    <script src="{% static 'js/passShowHide.js'%}"></script>
</body>
</html>

templates/userList.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User List</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel=" stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
</head>
<body>
    <div class="wrapper">
        <section class="user">
            <header>
                <div class="content">
                    <img src="{{ imguser }}" alt="">
                    <div class="detail">
                        <span>{{name}}</span>
                        <p>Active now</p>
                    </div>
                </div>
                <a href="{% url 'user:InfoUser' %}" class = "logout">Account</a>
                <a href="{% url 'user:Index' %}" class = "logout">Log out</a>
            </header>

            <form action="{% url 'user:SearchUser' %}">
                <div class="search" style="background-color: #ccc; border-radius: 5px; padding-left: 20px;">
                    <input type="text" placeholder="Enter name to search..." name="relative">
                    <button><i class="fas fa-search"></i></button>
                </div>
            </form>

            <div class="user-list">
                {% for u in users %}
                    <a href="{% url 'user:ChatDetail' u.id%}">
                        <div class="content">
                            <img src="{{ u.images }}" alt="">
                            <div class="detail">
                                <span>{{u.first_name}}  {{u.last_name}}</span>
                                <p>{{u.message}}</p>
                            </div>
                        </div>
                        <div class="status-dot"><i class="fas fa-circle"></i></div>
                    </a>
                {% endfor %}

            </div>
        </section>
    </div>

    <script src="{% static 'js/UserList.js' %}"></script>
</body>
</html>